AWSTemplateFormatVersion: "2010-09-09"
Description: ORCA Database

Parameters:
  ResourcePrefix:
    Type: String
    Default: hoge
  DBMasterUserPassword:
    Type: String
    Default: hogehoge
    NoEcho: true
#Mappings:
#Conditions:

Resources:
  ORCADBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${ResourcePrefix}-orca
      Engine: postgres
      EngineVersion: 10.5
      #LicenseModel: String
      DBInstanceClass: db.t2.small
      StorageType: gp2
      #Iops: Number
      AllocatedStorage: 10
      StorageEncrypted: false
      #KmsKeyId: String
      DBSubnetGroupName:
        Fn::ImportValue:
          !Sub ${ResourcePrefix}-ORCADBSubnetGroupName
      MultiAZ: false
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref AWS::Region
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Sub ${ResourcePrefix}-ORCADBSecurityGroupId
      Port: 5432
      PubliclyAccessible: false
      #DBName: String
      #DBParameterGroupName: String
      MasterUsername: postgres
      MasterUserPassword: !Ref DBMasterUserPassword
      #OptionGroupName: String
      MonitoringInterval: 0
      #MonitoringRoleArn: String
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      PreferredBackupWindow: 13:00-21:00
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      PreferredMaintenanceWindow: Sat:21:00-Sat:21:30
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-orca

    DeletionPolicy: Snapshot
Outputs:
  ORCADBInstanceEndpointAddress:
    Value: !GetAtt ORCADBInstance.Endpoint.Address
    Export:
      Name: !Sub ${ResourcePrefix}-ORCADBInstanceEndpointAddress

  ORCADBInstanceEndpointPort:
    Value: !GetAtt ORCADBInstance.Endpoint.Port
    Export:
      Name: !Sub ${ResourcePrefix}-ORCADBInstanceEndpointPort
