AWSTemplateFormatVersion: "2010-09-09"
Description: OpenVPN Server

Parameters:
  ResourcePrefix:
    Type: String
    Default: hoge
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0d7ed3ddb85b521a6
    Description: AMI ID for Amazon Linux 2(amzn2-ami-hvm-2.0.????????-x86_64-gp2)
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
  CAPemPassPhrase:
    Type: String
    Default: hogehoge
    NoEcho: true
#Mappings:
#Conditions:

Resources:
  OpenVPNServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          OpenVPNServer:
            - openvpn
          default:
            - ConfigSet: OpenVPNServer

        openvpn:
          packages:
            rpm:
              epel: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            yum:
              easy-rsa: []
              openvpn: []
          files:
            /etc/openvpn/server.conf:
              content: !Sub
                - |
                  port 443
                  proto tcp
                  dev tun
                  ca /usr/share/easy-rsa/3/pki/ca.crt
                  cert /usr/share/easy-rsa/3/pki/issued/server.crt
                  key /usr/share/easy-rsa/3/pki/private/server.key
                  dh /usr/share/easy-rsa/3/pki/dh.pem
                  server ${OpenVPNClientBaseIp} 255.255.255.0
                  ifconfig-pool-persist ipp.txt
                  push "route ${VPCBaseIp} 255.255.0.0"
                  keepalive 10 120
                  tls-auth ta.key 0
                  persist-key
                  persist-tun
                  status openvpn-status.log
                  verb 3
                  explicit-exit-notify 0
                - {
                    OpenVPNClientBaseIp: {"Fn::Select": ["0", "Fn::Split": ["/", {"Fn::ImportValue": {"Fn::Sub": "${ResourcePrefix}-OpenVPNClientCidrBlock"}}]]},
                    VPCBaseIp: {"Fn::Select": ["0", "Fn::Split": ["/", {"Fn::ImportValue": {"Fn::Sub": "${ResourcePrefix}-VPCCidrBlock"}}]]}
                  }
            /etc/sysctl.d/10-ipv4_forward.conf:
              content: "net.ipv4.ip_forward = 1"
            /etc/openvpn/client/client.ovpn:
              content: !Sub
                - |
                  client
                  dev tun
                  proto tcp
                  remote ${OpenVPNEIP} 443
                  resolv-retry infinite
                  nobind
                  persist-key
                  persist-tun
                  ca ca.crt
                  cert client.crt
                  key client.key
                  remote-cert-tls server
                  tls-auth ta.key 1
                  cipher AES-256-CBC
                  verb 3
                - {
                    OpenVPNEIP: {"Fn::ImportValue": {"Fn::Sub": "${ResourcePrefix}-OpenVPNEIP"}}
                  }
          commands:
            010_init_pki:
              command: "./easyrsa init-pki"
              cwd: /usr/share/easy-rsa/3
            011_build-ca:
              command: !Sub
                |
                ./easyrsa build-ca <<EOI
                ${CAPemPassPhrase}
                ${CAPemPassPhrase}
                Easy-RSA CA
                EOI
              cwd: /usr/share/easy-rsa/3
            012_gen-dh:
              command: ./easyrsa gen-dh
              cwd: /usr/share/easy-rsa/3
            013_build-server-full:
              command: !Sub
                |
                ./easyrsa build-server-full server nopass <<EOI
                ${CAPemPassPhrase}
                EOI
              cwd: /usr/share/easy-rsa/3
            014_build-client-full:
              command: !Sub
                |
                ./easyrsa build-client-full client nopass <<EOI
                ${CAPemPassPhrase}
                EOI
              cwd: /usr/share/easy-rsa/3
            020_genkey_tlskey:
              command: openvpn --genkey --secret /etc/openvpn/ta.key
            021_copy_clientset:
              command: |
                cp /usr/share/easy-rsa/3/pki/{ca.crt,issued/client.crt,private/client.key} ./client/
                cp /etc/openvpn/ta.key ./client/
                tar zcvf client.tar.gz ./client/
              cwd: /etc/openvpn
            022_start_openvpn:
              command: systemctl start openvpn@server && systemctl enable openvpn@server
            030_load_ipv4-foward:
              command: sysctl -p /etc/sysctl.d/10-ipv4_forward.conf

          #services:
          #  sysvinit:
          #    openvpn@server:
          #      enabled: true
          #      ensureRunning: true
          #      files:
          #        - /etc/openvpn/server.conf
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.nano
      KeyName: !Ref KeyPair
      InstanceInitiatedShutdownBehavior: stop
      #IamInstanceProfile: String
      #Monitoring: Boolean
      NetworkInterfaces:
        -
          DeviceIndex: 0
          DeleteOnTermination: false
          NetworkInterfaceId:
            Fn::ImportValue:
              !Sub ${ResourcePrefix}-OpenVPNNetworkInterfaceId
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            VolumeType: gp2
            VolumeSize: 10
      #EbsOptimized: Boolean
      SourceDestCheck: false
      UserData:
        Fn::Base64:
          !Join
            - "\n"
            - - "#!/bin/sh -x"
              - !Sub |
                /opt/aws/bin/cfn-init -v \
                  --region ${AWS::Region} \
                  --stack ${AWS::StackName} \
                  --resource OpenVPNServer
                result=$?
              - !Sub |
                /opt/aws/bin/cfn-signal \
                  --exit-code ${!result} \
                  --region ${AWS::Region} \
                  --stack ${AWS::StackName} \
                  --resource OpenVPNServer
      #AdditionalInfo: String
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-openvpn
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT15M
Outputs:
  OpenVPNConfigFile:
    Value: !Sub
      - scp -i ${KeyPair}.pem ec2-user@${OpenVPNEIP}:/etc/openvpn/client.tar.gz ./
      - {
          OpenVPNEIP: {"Fn::ImportValue": {"Fn::Sub": "${ResourcePrefix}-OpenVPNEIP"}}
        }
